## This function creates a list containing a functions to

## set the value of an input matrix "x" (which should be invertible)
## get the value of the matrix "x"
## set the value of the inverse matrix "inverseM" of "x"
## get the value of the inverse matrix "inverseM" of "x"

makeCacheMatrix <- function(x = matrix()) {
        inverseM <- NULL
        set <- function(y) {
                x <<- y
                inverseM <<- NULL
        }
        get <- function() x
        setinverse <- function(solve) inverseM <<- solve(x) 
        getinverse <- function() inverseM
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## This function returns the inverse matrix to a matrix "x" when applied to a list generated by the function "makeCacheMatrix(x)"

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inverseM <- x$getinverse()
        if(!is.null(inverseM)) {
                message("getting cached inverse matrix")
                return(inverseM)
        }
        data <- x$get()
        inverseM <- solve(data, ...)
        x$setinverse(inverseM)
        inverseM
}
